// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskScheduler.Models;

#nullable disable

namespace TaskScheduler.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskScheduler.Models.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Priority_pkey");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("TaskScheduler.Models.Recurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Recurrences_pkey");

                    b.ToTable("Recurrences");
                });

            modelBuilder.Entity("TaskScheduler.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RecurrenceTypeid")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Schedules_pkey");

                    b.HasIndex("RecurrenceTypeid");

                    b.HasIndex("StatusId");

                    b.HasIndex("TaskId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("TaskScheduler.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Statuses_pkey");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("TaskScheduler.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Tasks_pkey");

                    b.HasIndex("PriorityId");

                    b.HasIndex("TaskTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskScheduler.Models.TaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("TaskType_pkey");

                    b.ToTable("TaskTypes");
                });

            modelBuilder.Entity("TaskScheduler.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("Users_pkey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TaskScheduler.Models.Schedule", b =>
                {
                    b.HasOne("TaskScheduler.Models.Recurrence", "RecurrenceType")
                        .WithMany("Schedules")
                        .HasForeignKey("RecurrenceTypeid")
                        .IsRequired()
                        .HasConstraintName("Schedules_RecurrenceTypeid_fkey");

                    b.HasOne("TaskScheduler.Models.Status", "Status")
                        .WithMany("Schedules")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("Schedules_StatusId_fkey");

                    b.HasOne("TaskScheduler.Models.Task", "Task")
                        .WithMany("Schedules")
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("Schedules_TaskId_fkey");

                    b.Navigation("RecurrenceType");

                    b.Navigation("Status");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskScheduler.Models.Task", b =>
                {
                    b.HasOne("TaskScheduler.Models.Priority", "Priority")
                        .WithMany("Tasks")
                        .HasForeignKey("PriorityId")
                        .IsRequired()
                        .HasConstraintName("Tasks_PriorityId_fkey");

                    b.HasOne("TaskScheduler.Models.TaskType", "TaskType")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskTypeId")
                        .IsRequired()
                        .HasConstraintName("Tasks_TaskTypeId_fkey");

                    b.HasOne("TaskScheduler.Models.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Tasks_UserId_fkey");

                    b.Navigation("Priority");

                    b.Navigation("TaskType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskScheduler.Models.Priority", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskScheduler.Models.Recurrence", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TaskScheduler.Models.Status", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TaskScheduler.Models.Task", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TaskScheduler.Models.TaskType", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskScheduler.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
